### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by charlie2w** [Xiaoqi-Zhao-DLUT/MSNet#1]
Hi,
 I couldn't find the pre-trained models, "res2net50_v1b_26w_4s-3cf99910.pth", used in this code.
 Wish for your sincerely reply!

**Comment by charlie2w** [comment]
Hi,
I also have a question when I use the train.py

Traceback (most recent call last):
  File "D:/MSNet-main/train.py", line 85, in <module>
    train(dataset_medical, MSNet, LossNet)
  File "D:/MSNet-main/train.py", line 38, in train
    net = Network(cfg)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@charlie2w We upload the link of Res2Net weights in Readme  and update the train.py. You can try it again.

**Comment by charlie2w** [comment]
> @charlie2w We upload the link of Res2Net weights in Readme and update the train.py. You can try it again.

Thanks for your reply. Best wishes!
