### ISSUE TITLE
关于用于生成预测图部分的代码的一点问题

### ISSUE THREAD

**Issue by Alex-a233** [Xiaoqi-Zhao-DLUT/MSNet#10]
前辈您好！最近在研读您的论文（非常精彩的论文o(￣▽￣)ｄ）。然后尝试分析了一下您的代码，但是读到这里遇到了一点问题。

我理解您这里写的这个 crf_refine 方法是用来细化分割结果的对吗？
但是我回看您的论文发现并没有关于这个方法的任何描述，感觉很是奇怪。
请问这个是您用于调试时候留下的还是说您忘记在论文里对这一部分进行描述了？
![image](https://github.com/Xiaoqi-Zhao-DLUT/MSNet-M2SNet/assets/49720691/263683ec-16ee-4824-a563-ec6167457f3d)

**Comment by Xiaoqi-Zhao-DLUT** [comment]
crf是以前分割领域会采用的一种后处理手段，现在几乎不会使用了。 代码里面只是留出来了，可用可不用的。 论文里面汇报的结果都是没用采用crf的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月29日(周一) 晚上10:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Xiaoqi-Zhao-DLUT/MSNet-M2SNet] 关于用于生成预测图部分的代码的一点问题 (Issue #10)




 
前辈您好！最近在研读您的论文（非常精彩的论文o(￣▽￣)ｄ）。然后尝试分析了一下您的代码，但是读到这里遇到了一点问题。
 
我理解您这里写的这个 crf_refine 方法是用来细化分割结果的对吗？
 但是我回看您的论文发现并没有关于这个方法的任何描述，感觉很是奇怪。
 请问这个是您用于调试时候留下的还是说您忘记在论文里对这一部分进行描述了？
 image.png (view on web)

**Comment by Alex-a233** [comment]
OK，谢谢前辈的回复！
