### ISSUE TITLE
video polyp segment

### ISSUE THREAD

**Issue by SegmGod** [Xiaoqi-Zhao-DLUT/MSNet#11]
I would like to ask the Settings of data sets for video polyp segmentation in the author's experiment. Should the two data sets be used separately for training or mixed together for training? Thank you for your answer

**Comment by Xiaoqi-Zhao-DLUT** [comment]
Both of these two papers do not conduct experiments on the video polyp datasets.



---Original---
From: ***@***.***&gt;
Date: Wed, May 29, 2024 21:49 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Xiaoqi-Zhao-DLUT/MSNet-M2SNet] video polyp segment (Issue #11)




 
I would like to ask the Settings of data sets for video polyp segmentation in the author's experiment. Should the two data sets be used separately for training or mixed together for training? Thank you for your answer

**Comment by SegmGod** [comment]
![微信图片_20240530092537](https://github.com/Xiaoqi-Zhao-DLUT/MSNet-M2SNet/assets/148849904/9ac6133c-17a2-4d8b-814c-7228ba9a6857)
请问一下作者这个结果是怎么出来的呀，前面的数据集介绍也提到了视频息肉数据集，谢谢你的回答

**Comment by Xiaoqi-Zhao-DLUT** [comment]
不好意思，我前面说错了。论文里面写了：We follow the latest video polyp segmentation method to split the videos from CVC-300 (12
clips) and CVC-612 (29 clips) into 60% for training, 20% for
validation, and 20% for testing.
COVID-19 Lung Infection.&nbsp; 两个数据集混合在一起训练的



---Original---
From: ***@***.***&gt;
Date: Thu, May 30, 2024 09:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Xiaoqi-Zhao-DLUT/MSNet-M2SNet] video polyp segment (Issue #11)




 
_20240530092537.png (view on web)
 请问一下作者这个结果是怎么出来的呀，前面的数据集介绍也提到了视频息肉数据集，谢谢你的回答

**Comment by SegmGod** [comment]
好的好的谢谢您，混在一起训练，测试就是用三个数据集是把，另外您提供的训练数据集中ASU-Mayo_Clinic，是不是没用呢

**Comment by Xiaoqi-Zhao-DLUT** [comment]
yes



---Original---
From: ***@***.***&gt;
Date: Thu, May 30, 2024 09:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Xiaoqi-Zhao-DLUT/MSNet-M2SNet] video polyp segment (Issue #11)




 
好的好的谢谢您，混在一起训练，测试就是用三个数据集是把，另外您提供的训练数据集中ASU-Mayo_Clinic，是不是没用呢
