### ISSUE TITLE
evaluate score

### ISSUE THREAD

**Issue by SegmGod** [Xiaoqi-Zhao-DLUT/MSNet#8]
Hello author, I would like to ask that in the process of reproducing your code, after using your source code and data set, the same hyperparameters, and the training results for testing, it is estimated that the results in your paper are low, but using your There is nothing wrong with the weights provided. Could you please help me answer my doubts?

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@SegmGod you can directly test our prediction maps. And you can use this code [https://github.com/Xiaoqi-Zhao-DLUT/PySegMetric_EvalToolkit](url) to finish evaluating.
![image](https://github.com/Xiaoqi-Zhao-DLUT/MSNet-M2SNet/assets/25542131/9ea5fc08-9c63-4cf1-a026-88333ad5aba7)

**Comment by SegmGod** [comment]
@Xiaoqi-Zhao-DLUT Thank you !
