### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by SanmAIGO** [Xiaoqi-Zhao-DLUT/MSNet#9]
Hello author, first of all thank you for providing such a good job. While reading this article, I noticed that you used a lot of visual features in the Fig 8 , which is a good highlight. I was wondering if you could share your code for feature visualization with me. I will quote your article in my article.

**Comment by hnhhlp** [comment]
I think the picture in Figure 8 might be produced by saving the feature matrix of each layer as an image. Don't have feature visualization code。

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@SanmAIGO you can try and modify this code [https://github.com/Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency/blob/master/generate_visfeamaps.py](url) to meet your requirement.
